//Ejercicio 1
SELECT j.NOMBRE , j.APELLIDO_1 ,j.APELLIDO_2 , j.DNI as "Dni_jugador", e2.DNI as "Dni_entrenador"
FROM JUGADOR j join EQUIPO e on j.FK_ID_EQUIPO = e.PK_ID_EQUIPO
			   join ENTRENADOR e2 on e.FK_ID_ENTRENADOR = e2.PK_ID_ENTRENADOR;

//Ejercicio 2
SELECT j.NOMBRE , j.APELLIDO_1 ,j.APELLIDO_2 , j.DNI, e.NOMBRE
FROM JUGADOR j left join EQUIPO e on j.FK_ID_EQUIPO =e.PK_ID_EQUIPO ;

//Ejercicio 3
SELECT pr.NOMBRE, COUNT(j.PK_ID_JUGADOR)
FROM JUGADOR j join POBLACION po on j.FK_ID_POBLACION = po.PK_ID_POBLACION
			   right join PROVINCIA pr on pr.PK_ID_PROVINCIA = po.FK_ID_PROVINCIA
GROUP BY pr.NOMBRE;

//Ejercicio 4
SELECT g.PK_ID_GRUPO ,
CASE WHEN
		     (SELECT COUNT(j.PK_ID_JUGADOR)
			  FROM EQUIPO_GRUPO eg join EQUIPO e on eg.FK_ID_EQUIPO =e.PK_ID_EQUIPO
					 			   join JUGADOR j on j.FK_ID_EQUIPO = e.PK_ID_EQUIPO
			  WHERE g.PK_ID_GRUPO = eg.FK_ID_GRUPO AND
			  		j.FECHA_NACIMIENTO<'1994-01-01')>2
     THEN "Veteranos"
	 ELSE "Jovenes"
END AS Experiencia
FROM GRUPO g
GROUP BY g.PK_ID_GRUPO ;

//Ejercicio 5
SELECT j.PK_ID_JUGADOR , sum(p.SETS_LOCAL + p.SETS_VISITANTE) as "Num_sets"
FROM JUGADOR j join EQUIPO e on j.FK_ID_EQUIPO = e.PK_ID_EQUIPO
			   join PARTIDO p on e.PK_ID_EQUIPO = p.FK_ID_EQUIPO_LOCAL OR e.PK_ID_EQUIPO = p.FK_ID_EQUIPO_VISITANTE
GROUP BY j.PK_ID_JUGADOR
ORDER BY Num_sets desc
LIMIT 100000
OFFSET 2
