CREATE DATABASE GESTION_PEDIDOS;
USE DATABASE GESTION_PEDIDOS;

CREATE TABLE IF NOT EXISTS USUARIO(
	PK_ID_USUARIO int AUTO_INCREMENT,
	ROL ENUM('rider','admin'),
    USER_NAME varchar(255) UNIQUE,
    USER_PASSWORD varchar(255),
    NOMBRE varchar(255),
    APELLIDO_1 varchar(255),
    APELLIDO_2 varchar(255),
    CIUDAD varchar(255),
    PRIMARY KEY (PK_ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS PEDIDO(
	PK_ID_PEDIDO int AUTO_INCREMENT,
	REFERENCIA varchar(255) UNIQUE,
    ESTADO ENUM('pendiente','asignado','recogido','entregado'),
    DIRECCION_RECOGIDA varchar(255),
    HORA_RECOGIDA datetime,
    DIRECCION_ENTREGA varchar(255),
    HORA_ENTREGA datetime,
    DISTANCIA float,
    FK_ID_RIDER int,
    PRIMARY KEY (PK_ID_PEDIDO),
    FOREIGN KEY (FK_ID_RIDER) REFERENCES USUARIO(PK_ID_USUARIO)
);

INSERT INTO USUARIO (ROL, NOMBRE, APELLIDO_1, APELLIDO_2) VALUES ('rider','Miguel', 'Vallejo', 'Pérez');
INSERT INTO USUARIO (ROL, NOMBRE, APELLIDO_1, APELLIDO_2) VALUES ('rider','Alexander', 'Stockorov', NULL); //Nota mental no añadir como null
INSERT INTO USUARIO (ROL, NOMBRE, APELLIDO_1, APELLIDO_2) VALUES ('rider','Walter José', 'Ginolli', 'Martínez');
INSERT INTO USUARIO (ROL, NOMBRE, APELLIDO_1, APELLIDO_2) VALUES ('rider','Antonio', 'Gómez', 'López de la Torre');
INSERT INTO PEDIDO (REFERENCIA, ESTADO, DIRECCION_RECOGIDA, DIRECCION_ENTREGA) VALUES ('REF-0001','pendiente','Calle Villegas 2','Avenida de la Solidaridad 31');
INSERT INTO PEDIDO (REFERENCIA, ESTADO, DIRECCION_RECOGIDA, DIRECCION_ENTREGA) VALUES ('REF-0004','pendiente','Calle Eibar 1','Gran Vía 12');
INSERT INTO PEDIDO (REFERENCIA, ESTADO, DIRECCION_RECOGIDA, DIRECCION_ENTREGA, FK_ID_RIDER) VALUES ('REF-0070','asignado','Calle Rey Pastor 13','Calle Luis Barrón 23', 2);
INSERT INTO PEDIDO (REFERENCIA, ESTADO, DIRECCION_RECOGIDA, DIRECCION_ENTREGA, FK_ID_RIDER) VALUES ('REF-0006','asignado','Avenida Gonzalo de Berceo 3','Calle La Barrera 14', 3);
INSERT INTO PEDIDO (REFERENCIA, ESTADO, DIRECCION_RECOGIDA, DIRECCION_ENTREGA, FK_ID_RIDER, HORA_RECOGIDA) VALUES ('REF-0005-A','recogido','Calle Beti Jai 3','Calle 7 Infantes de Lara 4', 3, now());

//Query de getPedidos
SELECT P.*, CONCAT(U.NOMBRE," ",U.APELLIDO_1," ",U.APELLIDO_2) as "RIDER"
FROM PEDIDO P JOIN USUARIO U ON P.FK_ID_RIDER = U.PK_ID_USUARIO
